name: Deploy to GitHub Pages

on:
  push:
    branches:
      - "master"

jobs:
  publish:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Install Trunk
        run: cargo install --locked trunk

      - name: Add the wasm target
        run: rustup target add wasm32-unknown-unknown

      - name: Check out
        uses: actions/checkout@v3

      - name: Generate build artifacts
        run: trunk build --release --public-url /uoeo-eportfolio/

      - name: Publish contents of dist folder to root directory on gh-pages branch
        uses: rayluo/github-pages-overwriter@v1.3
        with:
          source-directory: dist
          target-branch: gh-pages
